spring:
  #JPA 配置
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        enableLazyLoadNoTrans: true
  #Mysql 数据源配置
  datasource:
    url: jdbc:mysql://172.18.81.247:3306/scar?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
#    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: P44VA6KIq35k@
#    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid: 
      filter:
        stat:
          enabled: true
          log-slow-sql: true
        wall:
          enabled: true
        config:
          enabled: true
      min-idle: 2
      max-active: 30
      initial-size: 2
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select x
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
  #redis配置
  redis:
    host: localhost
    port: 6379
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
   #配置输出 配置
logging:
  level:
    ROOT: INFO
    ORG:
      SPRINGFRAMEWORK:
        WEB: INFO
      HIBERNATE: INFO
  config: classpath:logback-boot.xml 
 #服务器配置
server:
#  address: localhost
  address: 172.18.81.246
  port: 80
  tomcat:
    max-connections: 65535
    uri-encoding: UTF-8
    
    